. /home/jimbo1qaz/miniconda3/etc/profile.d/conda.sh
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
. ~/.local/venvs/pyfunky/lib/python3.6/site-packages/scripts/shell/funky.sh
. ~/.aliases
