zstyle ':prezto:module:utility' safe-ops no
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
. ~/.local/venvs/pyfunky/lib/python3.6/site-packages/scripts/shell/funky.sh
. ~/.aliases
#. /home/jimbo1qaz/.zfunc/_poetry
